name: georgia-hello-world-pipeline
on: [push]
jobs:
  validate-lint-test-and-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: lint
      run: |
        ./bin/lint.sh

    - name: test
      run: |
        ./bin/test.sh

    - name: validate_build
      run: |
        ./bin/build.sh






